version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: token_manager_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    command: mix phx.server
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "ecto://postgres:postgres@db/token_manager_dev"
      DB_HOST: db

volumes:
  pgdata:
